apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkflow-students
  namespace: thinkflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thinkflow-students
  template:
    metadata:
      labels:
        app: thinkflow-students
    spec:
      containers:
        - name: thinkflow-students
          image: omkarbhute/thinkflow-students:26
          ports:
            - containerPort: 5001

          # ✅ ADD THIS (loads .env.students secret)
          envFrom:
            - secretRef:
                name: thinkflow-students-secret

          # ✅ ADD THIS (mount firebase + instance folder)
          volumeMounts:
            - name: firebase-volume
              mountPath: /app/nisarga-773f0-firebase-adminsdk-fbsvc-0121e2bef1.json
              subPath: nisarga-773f0-firebase-adminsdk-fbsvc-0121e2bef1.json

            - name: instance-volume
              mountPath: /app/instance

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

      # ✅ ADD THIS (define volumes)
      volumes:
        - name: firebase-volume
          secret:
            secretName: firebase-secret

        - name: instance-volume
          emptyDir: {}
