apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkflow-students
  namespace: thinkflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thinkflow-students
  template:
    metadata:
      labels:
        app: thinkflow-students
    spec:
      containers:
        - name: thinkflow-students
          image: omkarbhute/thinkflow-students:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
