apiVersion: apps/v1
kind: Deployment
metadata:
  name: thinkflow-teachers
  namespace: thinkflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thinkflow-teachers
  template:
    metadata:
      labels:
        app: thinkflow-teachers
    spec:
      containers:
        - name: thinkflow-teachers
          image: omkarbhute/thinkflow-teachers:27
          ports:
            - containerPort: 5000

          # ✅ Load .env.teachers secret
          envFrom:
            - secretRef:
                name: thinkflow-teachers-secret

          # ✅ Mount firebase + config + instance
          volumeMounts:
            # Firebase JSON
            - name: firebase-volume
              mountPath: /app/nisarga-773f0-firebase-adminsdk-fbsvc-0121e2bef1.json
              subPath: nisarga-773f0-firebase-adminsdk-fbsvc-0121e2bef1.json

            # Config folder (if you created secret from folder)
            - name: config-volume
              mountPath: /app/config

            # Instance folder (for SQLite or runtime files)
            - name: instance-volume
              mountPath: /app/instance

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"

      volumes:
        # Firebase file
        - name: firebase-volume
          secret:
            secretName: firebase-secret

        # Config folder secret
        - name: config-volume
          secret:
            secretName: thinkflow-config-secret

        # Writable runtime directory
        - name: instance-volume
          emptyDir: {}
